---
- name: "{{ hbase_task_prefix }} Download Phoenix checksum"
  ansible.builtin.uri:
    url: "{{ hbase_phoenix_url_checksum }}"
    return_content: true
  register: hbase_phoenix_download_checksum_raw

- name: "{{ hbase_task_prefix }} Extract Phoenix checksum"
  ansible.builtin.set_fact:
    hbase_phoenix_download_checksum: "{{ hbase_phoenix_download_checksum_raw.content.split(': ')[1] | regex_replace('\n','') | regex_replace(' ','') | lower }}"

- name: "{{ hbase_task_prefix }} Download Phoenix tarball"
  ansible.builtin.get_url:
    url: "{{ hbase_phoenix_url_file }}"
    dest: "{{ hbase_path_phoenix_tarball }}"
    checksum: "{{ hbase_phoenix_checksum_algo }}:{{ hbase_phoenix_download_checksum }}"

- name: "{{ hbase_task_prefix }} Unpack Phoenix tarball"
  ansible.builtin.unarchive:
    src: "{{ hbase_path_phoenix_tarball }}"
    dest: "{{ hbase_path_base }}"
    remote_src: true
    creates: "{{ hbase_path_phoenix_unpacked }}"

- name: "{{ hbase_task_prefix }} Copy Phoenix binaries"
  ansible.builtin.copy:
    src: "{{ hbase_path_phoenix_unpacked }}/"
    dest: "{{ hbase_path_phoenix_install }}"
    remote_src: true
    force: false

- name: "{{ hbase_task_prefix }} Link Phoenix library"
  ansible.builtin.file:
    state: link
    src: "{{ hbase_path_phoenix_install }}/phoenix-server-hbase-{{ hbase_phoenix_version_hbase }}-{{ hbase_phoenix_version }}.jar"
    dest: "{{ hbase_path_install }}/lib/phoenix-server-hbase-{{ hbase_phoenix_version_hbase }}-{{ hbase_phoenix_version }}.jar"


...
